#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

xbindkeys -f ~/.config/.xbindkeysrc &
picom  &
~/.screenlayout/main.sh &
udiskie &
nm-applet &
volumeicon &
easyeffects &
xclip &
~/.config/polybar/launch_polybar.sh &
conky --config ~/.config/conky/leftwm/conky.conf & 

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"
nitrogen --restore &  
