#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

xbindkeys -f ~/.config/leftwm/themes/gruvbox/.xbindkeysrc &
picom --config ~/.config/leftwm/themes/gruvbox/picom.conf &
conky -c ~/.config/leftwm/themes/gruvbox/conky.conf &
~/.screenlayout/main.sh &
nm-applet &
volumeicon &
pipewire & 
pipewire-pulse & 
wireplumber &
polybar -c ~/.config/leftwm/themes/gruvbox/config_polybar.ini &
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"
nitrogen --restore &  
